apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - ns: engineering-dev
        url: https://kubernetes.default.svc
      - ns: engineering-prod
  template:
    metadata:
      name: '{{.ns}}-guestbook'
    spec:
      project: default
      syncPolicy:
        automated: {}  
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: applicationset/examples/list-generator/guestbook/{{.ns}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.ns}}'
